- name: Setup new user on server
  hosts: api
  become: true
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Fail if user_password is not defined
      ansible.builtin.fail:
        msg: "The variable 'user_password' must be defined."
      when: user_password is not defined

    - name: Fail if ssh_keys is not defined
      ansible.builtin.fail:
        msg: "The variable 'ssh_keys' must be defined and contain at least one key."
      when: ssh_keys is not defined or ssh_keys | length == 0

  tasks:
    - name: Ensure the new user exists with a password
      ansible.builtin.user:
        name: genry_bolit
        comment: "New user for administration"
        create_home: yes
        shell: /bin/bash
        password: "{{ user_password | password_hash('sha512') }}"

    - name: Add the user to sudo group
      ansible.builtin.user:
        name: genry_bolit
        groups: sudo
        append: yes

    - name: Authorize SSH key for the new user
      ansible.builtin.file:
        path: /home/genry_bolit/.ssh
        state: directory
        mode: 0700
        owner: genry_bolit
        group: genry_bolit

    - name: Add multiple public keys to authorized_keys
      ansible.builtin.copy:
        dest: /home/genry_bolit/.ssh/authorized_keys
        content: "{{ ssh_keys | join('\n') }}"
        owner: genry_bolit
        group: genry_bolit
        mode: 0600

    - name: Configure passwordless sudo
      ansible.builtin.copy:
        dest: /etc/sudoers.d/genry_bolit
        content: "genry_bolit ALL=(ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: 0440

    - name: Install nvm
      become: true
      become_user: genry_bolit
      shell: >
        curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
        creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh

    - name: Install node and set version
      become: true
      become_user: genry_bolit
      shell: >
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 20 && nvm alias default 20"
        creates=/home/{{ ansible_user_id }}/.nvm/alias

    - name: Install pm2
      become: true
      become_user: genry_bolit
      shell: >
        npm i -g pm2
