name: Deploy server api

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to v3

      - name: Debug
        run: echo "$CRON_SSH_USER -> $CRON_SSH_HOST -> $env.CRON_SSH_PORT"

      - name: Use Node.js 22
        uses: actions/setup-node@v4  # Updated to v3
        with:
          node-version: 22
          #registry-url: https://npm.pkg.github.com/

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Remove old folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: "rm -rf /home/genry_bolit/nest/old"

      - name: Copy files to serve
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          rm: true
          source: "ecosystem.config.js,package.json,srt/*,src/db/migrations/*,public/*,dist/*,views/*,node_modules/*"
          target: "/home/${{ secrets.SSH_USERNAME }}/nest/next"

      - name: Copy files to cron
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.CRON_SSH_HOST }}
          username: ${{ env.CRON_SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ env.CRON_SSH_PORT }}
          rm: true
          source: "ecosystem.config.js,package.json,srt/*,src/db/migrations/*,public/*,dist/*,views/*,node_modules/*"
          target: "/home/${{ env.CRON_SSH_USER }}/apps/next"

      - name: Copy .env
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: "cp /home/genry_bolit/nest/.env /home/genry_bolit/nest/next/.env"

      - name: Copy .env on cron
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.CRON_SSH_HOST }}
          username: ${{ env.CRON_SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ env.CRON_SSH_PORT }}
          script: "cp /home/${{ env.CRON_SSH_USER }}/apps/.env /home/${{ env.CRON_SSH_USER }}/apps/next/.env"

      - name: Move folders
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: "mv /home/genry_bolit/nest/current /home/genry_bolit/nest/old && mv /home/genry_bolit/nest/next /home/genry_bolit/nest/current"

      - name: Move folders on cron
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.CRON_SSH_HOST }}
          username: ${{ env.CRON_SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ env.CRON_SSH_PORT }}
          script: "mv /home/${{ env.CRON_SSH_USER }}/apps/current /home/${{ env.CRON_SSH_USER }}/apps/old && mv /home/${{ env.CRON_SSH_USER }}/apps/next /home/${{ env.CRON_SSH_USER }}/apps/current"

      - name: Restart server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: "/home/genry_bolit/nest/restart.sh"

      - name: Restart cron server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.CRON_SSH_HOST }}
          username: ${{ env.CRON_SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ env.CRON_SSH_PORT }}
          script: "/home/${{ env.CRON_SSH_USER }}/apps/restart.sh"
